[package]
name = "idea-reaction"
version = "0.1.0"
edition = "2021"
description = "アイデア投稿履歴のリアクションを制限する Discord Bot"
authors = ["m1sk9 <me@m1sk9.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79" }
dotenvy = { version = "0.15.7" }
once_cell = { version = "1.19.0" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = { version = "0.9.31" }
envy = { version = "0.4.2" }

[dependencies.serenity]
version = "0.12.0"
features = ["client", "gateway", "model", "cache", "rustls_backend"]
default-features = false

[dependencies.tokio]
version = "1.35.1"
features = ["macros", "rt-multi-thread"]
