[package]
name = "idea-reaction"
version = "0.1.0"
edition = "2021"
description = "アイデア投稿履歴のリアクションを制限する Discord Bot"
authors = ["m1sk9 <me@m1sk9.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75" }
dotenvy = { version = "0.15.7" }
once_cell = { version = "1.18.0" }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }

[dependencies.serenity]
version = "0.11.6"
features = ["client", "gateway", "model", "cache", "rustls_backend"]
default-features = false

[dependencies.tokio]
version = "1.32.0"
features = ["macros", "rt-multi-thread"]
