name: Release idea-reaction-token

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish the Docker package
        uses: ./.github/actions/publish
        with:
          sha: ${{ github.sha }}
